### ISSUE TITLE
关于DASnet的结果

### ISSUE THREAD

**Issue by Luffy03** [louxiantuo/DASnet-train.txt-val.txt-#1]
您好！非常感谢您提供的txt和generate。请问您运行这个程序后的结果如何？是否达到论文中的精度？我有一些代码中的问题没有弄懂，想向您请教

**Comment by louxiantuo** [comment]
这篇文章，最终我没有仔细研究，我发现test通不太过，另外有一篇文章，跟这篇文章的代码几乎雷同，包括文章。

**Comment by Luffy03** [comment]
请问是哪篇论文呢？能不能分享下论文和代码连接？您在另一个代码的运行结果如何？非常感谢！

**Comment by louxiantuo** [comment]
https://github.com/lehaifeng/DASNet

**Comment by Luffy03** [comment]
您好，我还想请问下label里面的数据范围应该是【0，255】还是【0，1】？原来的数据是【0，255】，此时的loss总是很大还有负数。另外，我是一位刚接触cd task的学生，如果您不介意的话，我们是否可以留个微信或者qq交流一下？

**Comment by louxiantuo** [comment]
他这个文章问题蛮大的，我的loss，一直反复跳动，所以我认为文章本身可能是有问题的。这篇文章在意吧，另外，这个领域感觉不是很好搞，remote sensing上有很多水刊，顶会上也没多少论文。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Luffy03<mailto:notifications@github.com>
发送时间: 2020年7月13日 11:06
收件人: louxiantuo/DASnet-train.txt-val.txt-<mailto:DASnet-train.txt-val.txt-@noreply.github.com>
抄送: louxiantuo<mailto:louxiantuo@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [louxiantuo/DASnet-train.txt-val.txt-] 关于DASnet的结果 (#1)


您好，我还想请问下label里面的数据范围应该是【0，255】还是【0，1】？原来的数据是【0，255】，此时的loss总是很大还有负数。另外，我是一位刚接触cd task的学生，如果您不介意的话，我们是否可以留个微信或者qq交流一下？

―

**Comment by Luffy03** [comment]
确实，我也有这种感觉。但他这篇论文发在IEEE TGRS上，应该算是这个领域比较好了，而且精度也蛮高，所以还是想复现一下。非常感谢您的指导

**Comment by louxiantuo** [comment]
本来我也尝试着，去改学习率啥的，但是发现还是没什么用，遂放弃该论文。。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Luffy03<mailto:notifications@github.com>
发送时间: 2020年7月13日 14:08
收件人: louxiantuo/DASnet-train.txt-val.txt-<mailto:DASnet-train.txt-val.txt-@noreply.github.com>
抄送: louxiantuo<mailto:louxiantuo@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [louxiantuo/DASnet-train.txt-val.txt-] 关于DASnet的结果 (#1)


确实，我也有这种感觉。但他这篇论文发在IEEE TGRS上，应该算是这个领域比较好了，而且精度也蛮高，所以还是想复现一下。非常感谢您的指导

―
